### ISSUE TITLE
Doesn't work for 1.5.2

### ISSUE THREAD

**Issue by Micromic0** [YuLun-bili/Mod-Menu-Revamped#32]
I installed it correctly, but the menu doesn't work, only the original one shows up. Is that a problem only for me or is it global?

**Comment by YuLun-bili** [comment]
The menu would be reverted to vanilla every time game updates. This mod is working in 1.5.2(patch 2)

**Comment by Micromic0** [comment]
ok, I'll try again and say if it works or not

**Comment by Micromic0** [comment]
Yep, definitely works now, I just installed it wrong. Sorry!
