### ISSUE TITLE
Improvement towards search list right-click operation

### ISSUE THREAD

**Issue by Micromic0** [YuLun-bili/Mod-Menu-Revamped#40]
If I search for a mod and right-click it, the unsubscribe button doesn't pop up, but if you try to unsubscribe from the same mod without searching, you can unsubscribe just fine. This is a video showcasing the issue:

https://github.com/YuLun-bili/Mod-Menu-Revamped/assets/117858567/bc98cbc6-c761-4b57-8a43-2389abb3d96e

**Comment by YuLun-bili** [comment]
That's by design. You cannot perform operations towards mods in search mode since it can include mods from all three categories.

**Comment by Micromic0** [comment]
well then why not add some label saying from which category are they? Because searching in 100+ mods is kind of hard, especially if you want to unsubscribe from 1 specific one

**Comment by YuLun-bili** [comment]
would be added in menu v1.4.3
