### ISSUE TITLE
Menu not centered correctly on non 16:9 aspect ratio

### ISSUE THREAD

**Issue by Covkie** [YuLun-bili/Mod-Menu-Revamped#51]
![Screenshot_20240701_172237](https://github.com/YuLun-bili/Mod-Menu-Revamped/assets/52550063/cc5e70a6-4337-4d31-91d2-e367b4b0ab31)

**Comment by YuLun-bili** [comment]
that's 21:9

**Comment by YuLun-bili** [comment]
But as the game itself doesn't fully support other screen resolutions I'm not quite sure about what behaviour to choose at such cases. It could stretch to fit screen or just keep 16:9 ratio and try to fit in.

**Comment by YuLun-bili** [comment]
@Covkie 
<img src="https://github.com/YuLun-bili/Mod-Menu-Revamped/assets/70589524/658a69d8-4620-435c-8456-1d56e10409c1" width="640px"/>
<img src="https://github.com/YuLun-bili/Mod-Menu-Revamped/assets/70589524/d6f5a043-f01d-49c1-b9e7-8cb08b140408" width="320px"/>
