### ISSUE TITLE
Quick on/off collection

### ISSUE THREAD

**Issue by Quickness19** [YuLun-bili/Mod-Menu-Revamped#57]
add an on/off collection toggle. That would be pretty handy

![image](https://github.com/user-attachments/assets/a83ae7e3-ce7a-42e3-a8b9-fb324835473b)

**Comment by YuLun-bili** [comment]
you could do so by selecting the collection then right click on it, there's a dropdown menu with those options

**Comment by YuLun-bili** [comment]
closing, already implemented feature
